# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FigureGen.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1029, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.spinBox_alpha = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_alpha.setObjectName("spinBox_alpha")
        self.gridLayout.addWidget(self.spinBox_alpha, 2, 1, 1, 2)
        self.spinBox_MALength = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_MALength.setObjectName("spinBox_MALength")
        self.gridLayout.addWidget(self.spinBox_MALength, 1, 1, 1, 2)
        self.pbt_loadWave = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_loadWave.setObjectName("pbt_loadWave")
        self.gridLayout.addWidget(self.pbt_loadWave, 4, 0, 1, 1)
        self.label_MALength = QtWidgets.QLabel(self.centralwidget)
        self.label_MALength.setObjectName("label_MALength")
        self.gridLayout.addWidget(self.label_MALength, 1, 0, 1, 1)
        self.label_titleLoaded = QtWidgets.QLabel(self.centralwidget)
        self.label_titleLoaded.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titleLoaded.setObjectName("label_titleLoaded")
        self.gridLayout.addWidget(self.label_titleLoaded, 15, 0, 1, 3)
        self.label_alpha = QtWidgets.QLabel(self.centralwidget)
        self.label_alpha.setObjectName("label_alpha")
        self.gridLayout.addWidget(self.label_alpha, 2, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 6, 0, 2, 3)
        self.lineEdit_waveName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_waveName.setObjectName("lineEdit_waveName")
        self.gridLayout.addWidget(self.lineEdit_waveName, 9, 0, 1, 3)
        self.pbt_removeWave = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_removeWave.setObjectName("pbt_removeWave")
        self.gridLayout.addWidget(self.pbt_removeWave, 13, 0, 1, 3)
        self.pbt_waveColor = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_waveColor.setObjectName("pbt_waveColor")
        self.gridLayout.addWidget(self.pbt_waveColor, 12, 1, 1, 2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 14, 0, 1, 3)
        self.label_titleGlobal = QtWidgets.QLabel(self.centralwidget)
        self.label_titleGlobal.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titleGlobal.setObjectName("label_titleGlobal")
        self.gridLayout.addWidget(self.label_titleGlobal, 0, 0, 1, 3)
        self.label_showWave = QtWidgets.QLabel(self.centralwidget)
        self.label_showWave.setObjectName("label_showWave")
        self.gridLayout.addWidget(self.label_showWave, 11, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 16, 0, 1, 3)
        self.checkBox_showWave = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_showWave.setText("")
        self.checkBox_showWave.setObjectName("checkBox_showWave")
        self.gridLayout.addWidget(self.checkBox_showWave, 11, 1, 1, 2)
        self.pbt_showAll = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_showAll.setObjectName("pbt_showAll")
        self.gridLayout.addWidget(self.pbt_showAll, 3, 0, 1, 1)
        self.pbt_clearAll = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_clearAll.setObjectName("pbt_clearAll")
        self.gridLayout.addWidget(self.pbt_clearAll, 3, 1, 1, 2)
        self.label_waveColor = QtWidgets.QLabel(self.centralwidget)
        self.label_waveColor.setObjectName("label_waveColor")
        self.gridLayout.addWidget(self.label_waveColor, 12, 0, 1, 1)
        self.label_titleWave = QtWidgets.QLabel(self.centralwidget)
        self.label_titleWave.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titleWave.setObjectName("label_titleWave")
        self.gridLayout.addWidget(self.label_titleWave, 8, 0, 1, 3)
        self.pbt_removeAll = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_removeAll.setObjectName("pbt_removeAll")
        self.gridLayout.addWidget(self.pbt_removeAll, 4, 1, 1, 2)
        self.pbt_genFigure = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_genFigure.setObjectName("pbt_genFigure")
        self.gridLayout.addWidget(self.pbt_genFigure, 5, 0, 1, 3)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.horizontalLayout.setStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1029, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pbt_loadWave.setText(_translate("MainWindow", "加载波形"))
        self.label_MALength.setText(_translate("MainWindow", "滤波长度："))
        self.label_titleLoaded.setText(_translate("MainWindow", "已加载波形"))
        self.label_alpha.setText(_translate("MainWindow", "透明度："))
        self.pbt_removeWave.setText(_translate("MainWindow", "从工作区移除"))
        self.pbt_waveColor.setText(_translate("MainWindow", "PushButton"))
        self.label_titleGlobal.setText(_translate("MainWindow", "全局控制"))
        self.label_showWave.setText(_translate("MainWindow", "显示波形："))
        self.pbt_showAll.setText(_translate("MainWindow", "全部显示"))
        self.pbt_clearAll.setText(_translate("MainWindow", "全部隐藏"))
        self.label_waveColor.setText(_translate("MainWindow", "波形颜色："))
        self.label_titleWave.setText(_translate("MainWindow", "波形控制"))
        self.pbt_removeAll.setText(_translate("MainWindow", "全部移除"))
        self.pbt_genFigure.setText(_translate("MainWindow", "制图"))

