# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\wwxc9\Desktop\AI Study\RL\Code\2_GridWorld\UI\MapEditor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_self(object):
    def setupUi(self, self):
        self.setObjectName("self")
        self.resize(908, 659)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget.setMinimumSize(QtCore.QSize(600, 400))
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout_7.addWidget(self.gridWidget, 1, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 4, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_3.addWidget(self.spinBox, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 6, 0, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 7, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_3.addWidget(self.checkBox, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 5, 0, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_3.addWidget(self.spinBox_2, 2, 1, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_3.addWidget(self.spinBox_3, 3, 1, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout_3.addWidget(self.spinBox_4, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.pbt_deletePen = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_deletePen.setObjectName("pbt_deletePen")
        self.gridLayout.addWidget(self.pbt_deletePen, 3, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_7.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_7.addWidget(self.line_4, 1, 3, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_7.addWidget(self.line, 1, 1, 1, 1)
        self.generatorLayout = QtWidgets.QGridLayout()
        self.generatorLayout.setObjectName("generatorLayout")
        self.label_genTitle = QtWidgets.QLabel(self.centralwidget)
        self.label_genTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_genTitle.setObjectName("label_genTitle")
        self.generatorLayout.addWidget(self.label_genTitle, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.generatorLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setMinimumSize(QtCore.QSize(100, 0))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.generatorLayout.addWidget(self.line_5, 1, 0, 1, 1)
        self.generatorControlLayout = QtWidgets.QGridLayout()
        self.generatorControlLayout.setObjectName("generatorControlLayout")
        self.generatorLayout.addLayout(self.generatorControlLayout, 2, 0, 1, 1)
        self.gridLayout_7.addLayout(self.generatorLayout, 1, 4, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_7.addWidget(self.line_2, 0, 0, 1, 5)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_7.addWidget(self.line_3, 2, 0, 1, 5)
        self.gridLayout_7.setColumnStretch(2, 1)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 908, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuGenerator = QtWidgets.QMenu(self.menubar)
        self.menuGenerator.setObjectName("menuGenerator")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.action_new_map = QtWidgets.QAction(self)
        self.action_new_map.setObjectName("action_new_map")
        self.actionload_map = QtWidgets.QAction(self)
        self.actionload_map.setObjectName("actionload_map")
        self.actionsave = QtWidgets.QAction(self)
        self.actionsave.setObjectName("actionsave")
        self.actionsave_as = QtWidgets.QAction(self)
        self.actionsave_as.setObjectName("actionsave_as")
        self.actionCrossing_Wall = QtWidgets.QAction(self)
        self.actionCrossing_Wall.setObjectName("actionCrossing_Wall")
        self.menuFile.addAction(self.action_new_map)
        self.menuFile.addAction(self.actionload_map)
        self.menuFile.addAction(self.actionsave)
        self.menuFile.addAction(self.actionsave_as)
        self.menuGenerator.addAction(self.actionCrossing_Wall)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuGenerator.menuAction())

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "MainWindow"))
        self.label_6.setText(_translate("self", "右滑距离"))
        self.pushButton.setText(_translate("self", "修改方格"))
        self.pushButton_2.setText(_translate("self", "存为画笔"))
        self.label_4.setText(_translate("self", "下滑距离"))
        self.label_5.setText(_translate("self", "左滑距离"))
        self.label.setText(_translate("self", "方格设定"))
        self.label_3.setText(_translate("self", "上滑距离"))
        self.label_7.setText(_translate("self", "允许通行"))
        self.label_2.setText(_translate("self", "画笔设定"))
        self.label_9.setText(_translate("self", "开始绘制"))
        self.label_8.setText(_translate("self", "选择画笔"))
        self.pbt_deletePen.setText(_translate("self", "删除画笔"))
        self.label_genTitle.setText(_translate("self", "地图生成器"))
        self.menuFile.setTitle(_translate("self", "File"))
        self.menuGenerator.setTitle(_translate("self", "Generator"))
        self.action_new_map.setText(_translate("self", "new map"))
        self.actionload_map.setText(_translate("self", "load map"))
        self.actionsave.setText(_translate("self", "save"))
        self.actionsave_as.setText(_translate("self", "save as"))
        self.actionCrossing_Wall.setText(_translate("self", "Crossing Wall"))

