# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\wwxc9\Desktop\AI Study\RL\Code\2_GridWorld\UI\test.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 544)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 1, 1, 1)
        self.gridWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget.setMinimumSize(QtCore.QSize(600, 400))
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout_2.addWidget(self.gridWidget, 1, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 0, 0, 1, 3)
        self.settingLayout = QtWidgets.QVBoxLayout()
        self.settingLayout.setObjectName("settingLayout")
        self.cubeSettingLayout = QtWidgets.QGridLayout()
        self.cubeSettingLayout.setObjectName("cubeSettingLayout")
        self.label_cubePass = QtWidgets.QLabel(self.centralwidget)
        self.label_cubePass.setObjectName("label_cubePass")
        self.cubeSettingLayout.addWidget(self.label_cubePass, 5, 0, 1, 1)
        self.spinBox_cubeDown = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_cubeDown.setObjectName("spinBox_cubeDown")
        self.cubeSettingLayout.addWidget(self.spinBox_cubeDown, 2, 1, 1, 1)
        self.spinBox_cubeUp = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_cubeUp.setObjectName("spinBox_cubeUp")
        self.cubeSettingLayout.addWidget(self.spinBox_cubeUp, 1, 1, 1, 1)
        self.label_cubeTitle = QtWidgets.QLabel(self.centralwidget)
        self.label_cubeTitle.setObjectName("label_cubeTitle")
        self.cubeSettingLayout.addWidget(self.label_cubeTitle, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.label_cubeLeft = QtWidgets.QLabel(self.centralwidget)
        self.label_cubeLeft.setObjectName("label_cubeLeft")
        self.cubeSettingLayout.addWidget(self.label_cubeLeft, 3, 0, 1, 1)
        self.label_cubeRight = QtWidgets.QLabel(self.centralwidget)
        self.label_cubeRight.setObjectName("label_cubeRight")
        self.cubeSettingLayout.addWidget(self.label_cubeRight, 4, 0, 1, 1)
        self.pbt_editCube = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_editCube.setObjectName("pbt_editCube")
        self.cubeSettingLayout.addWidget(self.pbt_editCube, 6, 0, 1, 2)
        self.label_cubeDown = QtWidgets.QLabel(self.centralwidget)
        self.label_cubeDown.setObjectName("label_cubeDown")
        self.cubeSettingLayout.addWidget(self.label_cubeDown, 2, 0, 1, 1)
        self.checkBox_cubePass = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_cubePass.setText("")
        self.checkBox_cubePass.setObjectName("checkBox_cubePass")
        self.cubeSettingLayout.addWidget(self.checkBox_cubePass, 5, 1, 1, 1)
        self.spinBox_cubeLeft = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_cubeLeft.setObjectName("spinBox_cubeLeft")
        self.cubeSettingLayout.addWidget(self.spinBox_cubeLeft, 3, 1, 1, 1)
        self.label_cubeUp = QtWidgets.QLabel(self.centralwidget)
        self.label_cubeUp.setObjectName("label_cubeUp")
        self.cubeSettingLayout.addWidget(self.label_cubeUp, 1, 0, 1, 1)
        self.pbt_saveAsPen = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_saveAsPen.setObjectName("pbt_saveAsPen")
        self.cubeSettingLayout.addWidget(self.pbt_saveAsPen, 7, 0, 1, 2)
        self.spinBox_cubeRight = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_cubeRight.setObjectName("spinBox_cubeRight")
        self.cubeSettingLayout.addWidget(self.spinBox_cubeRight, 4, 1, 1, 1)
        self.settingLayout.addLayout(self.cubeSettingLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.settingLayout.addItem(spacerItem)

        self.penSettingLayout = QtWidgets.QGridLayout()
        self.penSettingLayout.setObjectName("penSettingLayout")
        self.comboBox_penName = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_penName.setObjectName("comboBox_penName")
        self.penSettingLayout.addWidget(self.comboBox_penName, 2, 1, 1, 1)
        self.checkBox_penDrawing = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_penDrawing.setText("")
        self.checkBox_penDrawing.setObjectName("checkBox_penDrawing")
        self.penSettingLayout.addWidget(self.checkBox_penDrawing, 3, 1, 1, 1)
        self.pbt_deletePen = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_deletePen.setObjectName("pbt_deletePen")
        self.penSettingLayout.addWidget(self.pbt_deletePen, 4, 0, 1, 2)
        self.label_penTitle = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_penTitle.sizePolicy().hasHeightForWidth())
        self.label_penTitle.setSizePolicy(sizePolicy)
        self.label_penTitle.setObjectName("label_penTitle")
        self.penSettingLayout.addWidget(self.label_penTitle, 1, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.label_penDrawing = QtWidgets.QLabel(self.centralwidget)
        self.label_penDrawing.setObjectName("label_penDrawing")
        self.penSettingLayout.addWidget(self.label_penDrawing, 3, 0, 1, 1)
        self.label_penName = QtWidgets.QLabel(self.centralwidget)
        self.label_penName.setObjectName("label_penName")
        self.penSettingLayout.addWidget(self.label_penName, 2, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.penSettingLayout.addWidget(self.line_4, 0, 0, 1, 2)
        self.settingLayout.addLayout(self.penSettingLayout)
        
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.settingLayout.addItem(spacerItem1)
        self.settingLayout.setStretch(3, 1)
        self.gridLayout_2.addLayout(self.settingLayout, 1, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 2, 0, 1, 3)
        self.gridLayout_2.setColumnStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 760, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_add_map = QtWidgets.QAction(MainWindow)
        self.action_add_map.setObjectName("action_add_map")
        self.action_load_map = QtWidgets.QAction(MainWindow)
        self.action_load_map.setObjectName("action_load_map")
        self.action_save_map = QtWidgets.QAction(MainWindow)
        self.action_save_map.setObjectName("action_save_map")
        self.menuFile.addAction(self.action_add_map)
        self.menuFile.addAction(self.action_load_map)
        self.menuFile.addAction(self.action_save_map)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_cubePass.setText(_translate("MainWindow", "允许通行"))
        self.label_cubeTitle.setText(_translate("MainWindow", "方格设定"))
        self.label_cubeLeft.setText(_translate("MainWindow", "左滑距离"))
        self.label_cubeRight.setText(_translate("MainWindow", "右滑距离"))
        self.pbt_editCube.setText(_translate("MainWindow", "修改方格"))
        self.label_cubeDown.setText(_translate("MainWindow", "下滑距离"))
        self.label_cubeUp.setText(_translate("MainWindow", "上滑距离"))
        self.pbt_saveAsPen.setText(_translate("MainWindow", "存为画笔"))
        self.pbt_deletePen.setText(_translate("MainWindow", "删除画笔"))
        self.label_penTitle.setText(_translate("MainWindow", "画笔设定"))
        self.label_penDrawing.setText(_translate("MainWindow", "开始绘制"))
        self.label_penName.setText(_translate("MainWindow", "选择画笔"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.action_add_map.setText(_translate("MainWindow", "new map"))
        self.action_load_map.setText(_translate("MainWindow", "load map"))
        self.action_save_map.setText(_translate("MainWindow", "save map"))

